# Generated by Django 5.0.6 on 2024-05-23 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=40, verbose_name='Название Технологии')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['technology'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=75, unique=True, verbose_name='Слаг проекта')),
                ('name_team', models.CharField(blank=True, max_length=20, verbose_name='Название команды')),
                ('team', models.TextField(blank=True, max_length=100, verbose_name='Состав команды')),
                ('task', models.TextField(blank=True, max_length=600, verbose_name='Задача')),
                ('solution', models.TextField(blank=True, max_length=800, verbose_name='Решение')),
                ('git_link', models.URLField(blank=True, verbose_name='Ссылка на репозиторий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.category', verbose_name='Категория проекта')),
                ('technologies', models.ManyToManyField(to='projects.technologies', verbose_name='Используемые технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография:')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_image', to='projects.project', verbose_name='Проект:')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='ProjectPresentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation', models.FileField(blank=True, upload_to='presentation/%Y/%m/%d', verbose_name='Презентация')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_presentation', to='projects.project', verbose_name='Проект:')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, verbose_name='Видео')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_video', to='projects.project', verbose_name='Проект:')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
