# Generated by Django 5.0.6 on 2024-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
    ]
