# Generated by Django 5.0.6 on 2024-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография для карточки:'),
        ),
    ]
