# Generated by Django 5.0.6 on 2024-05-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Фотография для карточки:'),
        ),
    ]
