# Generated by Django 5.0.6 on 2024-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1200, verbose_name='Описание'),
        ),
    ]
