# Generated by Django 5.0.6 on 2024-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/', help_text='https://www.youtube.com/embed/ ДОЛЖНО СТОЯТЬ ВНАЧАЛЕ ВМЕСТО https://www.youtube.com/', verbose_name='Видео'),
        ),
    ]
